### PR TITLE
Rust subworker

### PR DESCRIPTION
**Pull request by gavento**
Locally tested rust subworker with many tests, some finished APIs, docs.

Must be tested with: `cargo test -- --test-threads=1` (parallel tests clash their working dir settings)

Missing/WIP pieces include:
* [x] update on mutability/shared access to outputs and context from the task function
* [x] macros to add task functions with positional attributes
* attributes and content types with file/directory checking
* [x] (mostyl) more helper methods to `Context` and possibly `DataInstance`/`Output`.
* [x] build+testing in CI

### CODE REVIEW

**Comment by gavento** [comment]
@spirali Would you please take a look and test it against the worker? I am on a weak connection for the next few days and that complicates things. Also, feedback is welcome! (along with integration tests ;)

**Comment by spirali** [comment]
I have put basis for integration testing of rust subworker here: https://github.com/spirali/rain/commit/bc4cea8a44c9d1333a9fad898af51baa8410f773

* The tests expect that "rain-task-test" is built.
* I have merged some of my code for cpp subworker to avoid conflicts in testing.
* Test example is in test_rustsw.py

I will do some more review later.

**Comment by gavento** [comment]
Almost everything not dealing with attributes is finished and somewhat polished.

New and shiny docs and examples, many tests, flexible registration with `register_task!`, simplified writing to `Output` (no more built-in locks). There are still TODOs. Feedback welcome.

**Comment by gavento** [comment]
@spirali That sounds reasonable, do you want to open an issue/PR with a summary of the requirements, or make a writeup doc?

**Pull request merged**
